// Single source of truth for per-tool icon gradient backgrounds. Do NOT duplicate.
export const TOOL_ICON_BG: Record<string, string> = {
  // Analytics
  analyticsreport:               'bg-gradient-to-br from-blue-600 to-cyan-500',
  managetransaction:             'bg-gradient-to-br from-indigo-600 to-blue-500',
  expenses:                      'bg-gradient-to-br from-rose-500 to-red-600',
  credits:                       'bg-gradient-to-br from-emerald-500 to-green-600',
  'self-serve-analytics':        'bg-gradient-to-br from-blue-600 to-indigo-500',
  'autonomous-financial-analyst':'bg-gradient-to-br from-rose-600 to-pink-500',
  // Finance
  'smart-budget':       'bg-gradient-to-br from-emerald-500 to-teal-600',
  'smart-loan':         'bg-gradient-to-br from-green-600 to-emerald-500',
  'smart-sip':          'bg-gradient-to-br from-lime-500 to-green-600',
  'smart-net-worth':    'bg-gradient-to-br from-sky-500 to-blue-600',
  'smart-retirement':   'bg-gradient-to-br from-blue-600 to-indigo-500',
  'gst-calculator':     'bg-gradient-to-br from-orange-500 to-amber-600',
  'fire-calc':          'bg-gradient-to-br from-orange-500 to-red-500',
  'cost-of-delay':      'bg-gradient-to-br from-blue-500 to-cyan-500',
  'debt-planner':       'bg-gradient-to-br from-blue-600 to-indigo-500',
  'portfolio-rebalance':'bg-gradient-to-br from-teal-500 to-cyan-600',
  'ctc-calc':           'bg-gradient-to-br from-indigo-500 to-blue-600',
  'hra-calc':           'bg-gradient-to-br from-sky-500 to-indigo-500',
  'gratuity-calc':      'bg-gradient-to-br from-amber-500 to-yellow-500',
  'capital-gains-calc': 'bg-gradient-to-br from-indigo-600 to-blue-500',
  'tax-saving-compare': 'bg-gradient-to-br from-indigo-600 to-blue-500',
  'sub-audit':          'bg-gradient-to-br from-pink-500 to-rose-500',
  'wedding-budget':     'bg-gradient-to-br from-rose-500 to-pink-600',
  'salary-nego':        'bg-gradient-to-br from-blue-600 to-sky-500',
  'fd-calculator':      'bg-gradient-to-br from-amber-500 to-orange-500',
  'nps-calculator':     'bg-gradient-to-br from-teal-600 to-emerald-500',
  'ppf-calculator':     'bg-gradient-to-br from-green-600 to-teal-500',
  // Business
  'invoice-generator':'bg-gradient-to-br from-blue-600 to-blue-800',
  'salary-slip':      'bg-gradient-to-br from-indigo-600 to-blue-700',
  'smart-agreement':  'bg-gradient-to-br from-slate-600 to-slate-900',
  'id-card':          'bg-gradient-to-br from-cyan-500 to-teal-600',
  'rent-receipt':     'bg-gradient-to-br from-teal-500 to-emerald-600',
  // Documents
  'universal-converter':'bg-gradient-to-br from-amber-500 to-orange-600',
  'smart-scan':        'bg-gradient-to-br from-blue-500 to-cyan-500',
  'smart-pdf-merge':   'bg-gradient-to-br from-red-600 to-rose-500',
  'smart-pdf-split':   'bg-gradient-to-br from-rose-500 to-pink-600',
  'smart-img-compress':'bg-gradient-to-br from-pink-500 to-rose-500',
  'smart-img-convert': 'bg-gradient-to-br from-pink-500 to-rose-500',
  'smart-ocr':         'bg-gradient-to-br from-blue-600 to-indigo-600',
  'smart-word':        'bg-gradient-to-br from-slate-600 to-slate-800',
  'smart-excel':       'bg-gradient-to-br from-emerald-600 to-green-700',
  'json-csv':          'bg-gradient-to-br from-yellow-500 to-amber-600',
  // Developer
  'dev-station':    'bg-gradient-to-br from-indigo-600 to-blue-700',
  'api-playground': 'bg-gradient-to-br from-blue-500 to-cyan-600',
  'smart-jwt':      'bg-gradient-to-br from-pink-500 to-rose-500',
  'smart-json':     'bg-gradient-to-br from-orange-500 to-amber-500',
  'smart-sql':      'bg-gradient-to-br from-cyan-600 to-teal-500',
  'cron-gen':       'bg-gradient-to-br from-slate-500 to-gray-700',
  'git-cheats':     'bg-gradient-to-br from-red-600 to-orange-500',
  'smart-diff':     'bg-gradient-to-br from-indigo-500 to-blue-600',
  'regex-tester':   'bg-gradient-to-br from-amber-500 to-yellow-600',
  'hash-gen':       'bg-gradient-to-br from-emerald-500 to-teal-600',
  'num-convert':    'bg-gradient-to-br from-sky-600 to-blue-700',
  'timestamp-tool': 'bg-gradient-to-br from-sky-500 to-cyan-600',
  // Productivity
  'life-os':    'bg-gradient-to-br from-rose-500 to-pink-600',
  'qr-code':    'bg-gradient-to-br from-slate-700 to-slate-900',
  'smart-pass': 'bg-gradient-to-br from-emerald-500 to-green-600',
  'pomodoro':   'bg-gradient-to-br from-red-500 to-orange-500',
  // Converters
  'unit-convert':  'bg-gradient-to-br from-cyan-500 to-sky-600',
  'case-convert':  'bg-gradient-to-br from-orange-500 to-amber-500',
  // Design
  'color-picker':  'bg-gradient-to-br from-pink-500 to-rose-600',
  'color-studio':  'bg-gradient-to-br from-pink-500 to-fuchsia-400',
  // Health
  'smart-bmi':     'bg-gradient-to-br from-teal-500 to-cyan-600',
  'smart-breath':  'bg-gradient-to-br from-sky-500 to-blue-600',
  'smart-workout': 'bg-gradient-to-br from-lime-500 to-green-600',
  // AI
  'prompt-generator': 'bg-gradient-to-br from-pink-500 to-rose-500',
  'smart-chat':       'bg-gradient-to-br from-indigo-500 to-sky-500',
  'smart-analyze':    'bg-gradient-to-br from-blue-700 to-indigo-600',
  // Creator
  'audio-transcription': 'bg-gradient-to-br from-rose-500 to-orange-500',
  // Business OS
  'biz-dashboard':    'bg-gradient-to-br from-blue-600 to-indigo-600',
  'biz-daybook':      'bg-gradient-to-br from-emerald-500 to-teal-600',
  'biz-parties':      'bg-gradient-to-br from-indigo-500 to-blue-600',
  'biz-invoices':     'bg-gradient-to-br from-amber-500 to-orange-500',
  'biz-products':     'bg-gradient-to-br from-cyan-500 to-blue-500',
  'biz-inventory':    'bg-gradient-to-br from-teal-500 to-emerald-500',
  'biz-stock-entry':  'bg-gradient-to-br from-sky-500 to-cyan-500',
  'biz-reports':      'bg-gradient-to-br from-indigo-500 to-blue-600',
  'biz-outstanding':  'bg-gradient-to-br from-rose-500 to-red-600',
  'biz-purchases':    'bg-gradient-to-br from-blue-600 to-indigo-500',
  'biz-quotations':   'bg-gradient-to-br from-sky-400 to-blue-500',
  'biz-staff':        'bg-gradient-to-br from-pink-500 to-rose-500',
  'biz-gst':          'bg-gradient-to-br from-green-500 to-emerald-600',
  'biz-cashflow':     'bg-gradient-to-br from-lime-500 to-green-500',
  'biz-loans':        'bg-gradient-to-br from-red-500 to-rose-600',
  // Personal Finance
  'pf-statement-manager':  'bg-gradient-to-br from-blue-500 to-indigo-600',
  'pf-financial-position': 'bg-gradient-to-br from-emerald-500 to-teal-500',
  'pf-cash-flow':          'bg-gradient-to-br from-teal-500 to-cyan-500',
  'pf-tx-explorer':        'bg-gradient-to-br from-sky-500 to-blue-600',
  'pf-expenditure':        'bg-gradient-to-br from-rose-500 to-pink-500',
  'pf-expenses':           'bg-gradient-to-br from-red-500 to-rose-600',
  'pf-commitments':        'bg-gradient-to-br from-amber-500 to-orange-500',
  'pf-recurring':          'bg-gradient-to-br from-cyan-500 to-sky-500',
  'pf-top-merchants':      'bg-gradient-to-br from-orange-500 to-amber-600',
  'pf-big-spends':         'bg-gradient-to-br from-red-600 to-orange-500',
  'pf-rules':              'bg-gradient-to-br from-slate-600 to-slate-800',
  'pf-income-sources':     'bg-gradient-to-br from-green-500 to-emerald-600',
  'pf-behavior':           'bg-gradient-to-br from-blue-600 to-indigo-500',
  'pf-savings-trend':      'bg-gradient-to-br from-lime-500 to-green-500',
  'pf-month-compare':      'bg-gradient-to-br from-sky-500 to-blue-600',
  'pf-heatmap':            'bg-gradient-to-br from-fuchsia-500 to-pink-500',
  'pf-subscriptions':      'bg-gradient-to-br from-indigo-500 to-blue-500',
  'pf-labels':             'bg-gradient-to-br from-pink-500 to-rose-500',
  'pf-liability':          'bg-gradient-to-br from-yellow-500 to-amber-600',
  'pf-ai-analyst':         'bg-gradient-to-br from-indigo-600 to-sky-500',
  // Personal CRM
  'crm-people':       'bg-gradient-to-br from-indigo-500 to-blue-600',
  // Biz CRM
  'biz-crm-pipeline': 'bg-gradient-to-br from-indigo-500 to-blue-600',
  // Daily Utility
  'smart-cart': 'bg-gradient-to-br from-green-500 to-emerald-600',
};
