export default function Page() {
  return (
    <div className="p-8 bg-surface dark:bg-slate-800 dark:bg-surface shadow-lg shadow-slate-200/50 dark:shadow-none rounded-xl">
      <h1 className="text-2xl font-semibold mb-2">Tool Page</h1>
      <p>This is a placeholder generated by OTS scaffolding.</p>
    </div>
  );
}
