export default function Page() {
  return (
    <div className="p-8 bg-white shadow-sm rounded-xl">
      <h1 className="text-2xl font-semibold mb-2">Tool Page</h1>
      <p>This is a placeholder generated by OTS scaffolding.</p>
    </div>
  );
}
