// Category-level SEO keyword clusters used on category index pages
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'My Finance': [
    'personal finance tracker India',
    'bank statement analyzer free',
    'expense manager India',
    'income expense tracker',
    'transaction categorizer',
    'personal finance tools free',
    'financial calculator free India',
    'EMI calculator',
    'SIP calculator India',
    'GST calculator',
    'budget planner free',
    'retirement calculator India',
    'net worth calculator',
    'GST calculator India',
    'CGST SGST calculator',
    'reverse GST calculator',
    'GST rate finder',
    'tax calculator India free',
    'income tax calculator',
  ],
  'My Business': [
    'business management tools India',
    'small business OS free',
    'GST invoice daybook',
    'party ledger khata',
    'business dashboard free',
    'P&L report tool India',
  ],
};
