// Category-level SEO keyword clusters used on category index pages
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'Personal Finance': [
    'personal finance tracker India',
    'bank statement analyzer free',
    'expense manager India',
    'income expense tracker',
    'transaction categorizer',
    'personal finance tools free',
  ],
  'Personal CRM': [
    'personal CRM free',
    'contact relationship manager',
    'personal network tracker',
    'relationship management tool',
  ],
  'Business CRM': [
    'business CRM free',
    'customer relationship management tool',
    'sales pipeline tracker',
    'lead management free',
  ],
  'Business OS': [
    'business management tools India',
    'small business OS free',
    'GST invoice daybook',
    'party ledger khata',
    'business dashboard free',
    'P&L report tool India',
  ],
  Finance: [
    'financial calculator free India',
    'EMI calculator',
    'SIP calculator India',
    'GST calculator',
    'budget planner free',
    'retirement calculator India',
    'net worth calculator',
  ],
  'GST & Tax': [
    'GST calculator India',
    'CGST SGST calculator',
    'reverse GST calculator',
    'GST rate finder',
    'tax calculator India free',
    'income tax calculator',
  ],
  'Real Estate': [
    'real estate calculator India',
    'home loan EMI calculator',
    'property value estimator',
    'rent vs buy calculator',
    'stamp duty calculator India',
  ],
  Career: [
    'career planning tool free',
    'resume builder online',
    'salary calculator India',
    'job offer comparison tool',
    'career growth planner',
  ],
  Startup: [
    'startup tools free',
    'pitch deck builder',
    'startup financial model',
    'business plan tool',
    'MVP planner online',
  ],
  Travel: [
    'travel planner free online',
    'trip budget calculator',
    'itinerary planner',
    'travel expense tracker',
    'currency converter travel',
  ],
  Business: [
    'business document generator free',
    'GST invoice generator India',
    'salary slip generator',
    'rent receipt maker',
    'ID card generator',
    'legal agreement template',
    'business tools free India',
  ],
  Documents: [
    'PDF tools free online',
    'merge PDF online',
    'compress image free',
    'document converter browser',
    'PDF split free',
    'OCR online free',
    'image converter online',
  ],
  Developer: [
    'developer tools online free',
    'JSON formatter',
    'JWT decoder',
    'regex tester online',
    'SQL formatter free',
    'API tester browser',
    'coding utilities free',
    'web developer toolkit',
  ],
  Productivity: [
    'productivity tools free online',
    'QR code generator',
    'password generator free',
    'Pomodoro timer online',
    'life planner browser',
    'habit tracker free',
  ],
  Converters: [
    'unit converter online free',
    'length weight temperature converter',
    'text case converter',
    'metric imperial converter',
    'number base converter',
    'online conversion tool',
  ],
  Design: [
    'design tools free online',
    'color picker web',
    'CSS gradient generator',
    'HEX RGB color converter',
    'color palette generator free',
  ],
  Health: [
    'health calculator free online',
    'BMI calculator India',
    'HIIT workout timer',
    'breathing exercise tool',
    'fitness tracker browser',
  ],
  AI: [
    'AI tools free online',
    'AI prompt generator',
    'AI chat assistant free',
    'sentiment analyzer free',
    'ChatGPT alternative free',
    'AI writing tool browser',
  ],
  Creator: [
    'content creator tools free',
    'audio to text free',
    'speech to text browser',
    'transcription tool online',
    'live transcription free',
  ],
};
